/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseAlert: typeof import('./components/BaseAlert.vue')['default']
    BaseButton: typeof import('./components/BaseButton.vue')['default']
    BaseDialog: typeof import('./components/BaseDialog.vue')['default']
    BaseSelect: typeof import('./components/BaseSelect.vue')['default']
    MemoForm: typeof import('./components/MemoForm.vue')['default']
    RequiredTextArea: typeof import('./components/RequiredTextArea.vue')['default']
    RequiredTextField: typeof import('./components/RequiredTextField.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./components/SideBar.vue')['default']
    TopBar: typeof import('./components/TopBar.vue')['default']
  }
}
